### Assignment 7: Numpy

##### Q1: Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [8]:
import numpy as np

In [9]:
def output(inp,n,increasing):
    if increasing:
        mat = np.array([x**(n-1-i) for x in inp for i in range(n)]).reshape(inp.size,n)
    else:
        mat = np.array([x**i for x in inp for i in range(n)]).reshape(inp.size,n)
    return mat

In [11]:
inp=np.array([1,2,3,4,5])
n=int(input('Enter the no. of columns in output matrix'))

dec_order=output(inp,n,False)
inc_order=output(inp,n,True)

print('Output Matrix in decreasing order:\n',dec_order)
print('Output Matrix in increasing order:\n',inc_order)

Enter the no. of columns in output matrix3
Output Matrix in decreasing order:  [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
Output Matrix in increasing order:  [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


##### Q2: Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [12]:
def moving_average(li,k):
    cum, mov_avg = [0], []
    for i, x in enumerate(li, 1):
        cum.append(cum[i-1] + x) 
        if i>=k:
            mov_avg.append(round(((cum[i] - cum[i-k])/k),2)) 
    return mov_avg

In [15]:
my_list=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
win=3
res=moving_average(my_list,win)
print('Moving Average:',res)

Moving Average: 5.0 4.67 5.67 6.67 9.67 28.67 49.33 72.67 84.0 93.33 116.33
